### ISSUE TITLE
Simplify Functions

### ISSUE THREAD

**Issue by lfelipesv** [drumpt/blockly#3]
# Functions to simplify (make variables needed as input to the function hidden)

Ex: predict_ball(cur_ball, previous_ball) -> predict ball 

- [x] predict_ball
- [x] find_closest_robot
- [x] ball_is_own_goal
- [x] ball_is_own_penalty
- [x] ball_is_own_field
- [x] ball_is_opp_goal
- [x] ball_is_opp_penalty
- [x] ball_is_opp_field
- [x] get_defense_kick_angle
- [x] get_attack_kick_angle

# Functions to delete

- [x] set_wheel_velocity

**Comment by drumpt** [comment]
I modified all of them
